<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderAgenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('order_agen')->insert([
            [
                'id_user_agen' => 1,
                'jumlah' => 3,
                'total' => 510000,
                'tanggal' => '2024-08-01',
                'bukti_transfer' => 'transfer_01.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 2,
                'jumlah' => 5,
                'total' => 850000,
                'tanggal' => '2024-08-02',
                'bukti_transfer' => 'transfer_02.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 3,
                'jumlah' => 7,
                'total' => 1190000,
                'tanggal' => '2024-08-03',
                'bukti_transfer' => 'transfer_03.jpg',
                'status_pemesanan' => 0,
                'nota' => 'NOTA003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 4,
                'jumlah' => 2,
                'total' => 340000,
                'tanggal' => '2024-08-04',
                'bukti_transfer' => 'transfer_04.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 5,
                'jumlah' => 4,
                'total' => 680000,
                'tanggal' => '2024-08-05',
                'bukti_transfer' => 'transfer_05.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 1,
                'jumlah' => 6,
                'total' => 1020000,
                'tanggal' => '2024-08-06',
                'bukti_transfer' => 'transfer_06.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA006',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 2,
                'jumlah' => 8,
                'total' => 1360000,
                'tanggal' => '2024-08-07',
                'bukti_transfer' => 'transfer_07.jpg',
                'status_pemesanan' => 0,
                'nota' => 'NOTA007',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 3,
                'jumlah' => 5,
                'total' => 850000,
                'tanggal' => '2024-08-08',
                'bukti_transfer' => 'transfer_08.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA008',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 4,
                'jumlah' => 3,
                'total' => 510000,
                'tanggal' => '2024-08-09',
                'bukti_transfer' => 'transfer_09.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA009',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 5,
                'jumlah' => 7,
                'total' => 1190000,
                'tanggal' => '2024-08-10',
                'bukti_transfer' => 'transfer_10.jpg',
                'status_pemesanan' => 0,
                'nota' => 'NOTA010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 1,
                'jumlah' => 4,
                'total' => 680000,
                'tanggal' => '2024-08-11',
                'bukti_transfer' => 'transfer_11.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA011',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 2,
                'jumlah' => 9,
                'total' => 1530000,
                'tanggal' => '2024-08-12',
                'bukti_transfer' => 'transfer_12.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA012',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 3,
                'jumlah' => 2,
                'total' => 340000,
                'tanggal' => '2024-08-13',
                'bukti_transfer' => 'transfer_13.jpg',
                'status_pemesanan' => 0,
                'nota' => 'NOTA013',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 4,
                'jumlah' => 6,
                'total' => 1020000,
                'tanggal' => '2024-08-14',
                'bukti_transfer' => 'transfer_14.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA014',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 5,
                'jumlah' => 8,
                'total' => 1360000,
                'tanggal' => '2024-08-15',
                'bukti_transfer' => 'transfer_15.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA015',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 1,
                'jumlah' => 10,
                'total' => 1700000,
                'tanggal' => '2024-08-16',
                'bukti_transfer' => 'transfer_16.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA016',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user_agen' => 2,
                'jumlah' => 5,
                'total' => 850000,
                'tanggal' => '2024-08-17',
                'bukti_transfer' => 'transfer_17.jpg',
                'status_pemesanan' => 1,
                'nota' => 'NOTA017',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
